name: 简易构建

on:
  workflow_dispatch:  # 允许手动触发工作流

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v4.2.2

      - name: 设置 JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: 构建项目
        run: ./gradlew build
